### PR TITLE
refactor: DRY refactor on backend

### PR DESCRIPTION
**Pull request by wfxr**
Define `Backend` once in each `store.go` and use it elsewhere.

### CODE REVIEW

**Review by YikSanChan — APPROVED** [review]
lgtm. does it need to be public?

**Review by jinghancc — APPROVED** [review]
LGTM

**Comment by wfxr** [comment]
@YikSanChan You mean adding it to `Store` interface ?

**Review by lianxmfor — APPROVED** [review]
lgtm

**Pull request merged**
