### PR TITLE
feature: add health check api for oomstore

### LINKED ISSUE #675: Add health check api for `oomstore` and `oomagent`
Tasks:
- [x] #722
- [x] #676

### LINKED ISSUE #722: add health check api for `oomstore`

### PR DESCRIPTION
**Pull request by wfxr**
Close #722
Close #675

### CODE REVIEW

**Comment by lianxmfor** [comment]
How about calling the ping function when the oomstore is initialized?

**Review by jinghancc — APPROVED** [review]
LGTM

**Comment by wfxr** [comment]
@lianxmfor Not sure what do you mean by "when oomstore is initialized" ?

**Comment by lianxmfor** [comment]
> @lianxmfor Not sure what do you mean by "when oomstore is initialized" ?

when call `oomstore.Open()`

**Comment by wfxr** [comment]
> > @lianxmfor Not sure what do you mean by "when oomstore is initialized" ?
>
> when call `oomstore.Open()`

@lianxmfor Maybe no necessary ? Databases like `pg` and `redis` also never call `Ping` in `Open` fucntion.

**Pull request merged**
