### PR TITLE
refactor(database/metadata): set full_name as unique key

### PR DESCRIPTION
**Pull request by jinghancc**

### CODE REVIEW

**Review by YikSanChan — APPROVED** [review]
lgtm

**Comment by wfxr** [comment]
@jinghancc How about instead adding an unique constraint to `name` and `group` ?

**Comment by jinghancc** [comment]
> @jinghancc How about instead adding an unique constraint to `name` and `group` ? In the future we may remove the `full_name` field because it can be easily concated by `group:name`.

@wfxr do you mean `UNIQUE(group_id, name)`?

**Comment by wfxr** [comment]
> @wfxr do you mean `UNIQUE(group_id, name)`?

@jinghancc exactly

**Comment by jinghancc** [comment]
> > @wfxr do you mean `UNIQUE(group_id, name)`?
> 
> @jinghancc exactly

@wfxr sounds good, done!

**Pull request merged**
