### PR TITLE
Jinghan/merge `list feature` and `describe feature` to `get meta feature`

### PR DESCRIPTION
**Pull request by jinghancc**
This PR combines `list feature` and `describe feature` to `get meta feature`.

related to #651

### CODE REVIEW

**Comment by lianxmfor** [comment]
Does the `-o yaml` option wait until after the migration?

**Comment by jinghancc** [comment]
> Does the `-o yaml` option wait until after the migration?

@lianxmfor yes, this should be done in another PR, tracked in issue #694

**Comment by lianxmfor** [comment]
The command `describe feature` can now be deleted?

**Review by YikSanChan — APPROVED** [review]
lgtm

**Comment by jinghancc** [comment]
> The command `describe feature` can now be deleted?

deleted!

**Pull request merged**
