### PR TITLE
fix: open tidb

### PR DESCRIPTION
**Pull request by YikSanChan**

### CODE REVIEW

**Review by wfxr — COMMENTED** [review]
This logic feels some weird. Why not add a new dedicate enum `TiDB` ?

**Comment by YikSanChan** [comment]
@wfxr because tidb and mysql share the same backend type. Having a separate backend type will add quite some code.

**Comment by wfxr** [comment]
@YikSanChan I mean just add a dedicate backend enum:
```
	switch opt.Backend {
	case types.BackendPostgres:
		return onlinePG.Open(opt.Postgres)
	case types.BackendRedis:
		return onlineRedis.Open(opt.Redis), nil
	case types.BackendMySQL, types.BackendTiDB:
		return onlineMySQL.Open(opt.TiDB)
	case types.BackendDynamoDB:
		return onlineDynamoDB.Open(opt.DynamoDB)
	case types.BackendCassandra:
		return onlineCassandra.Open(opt.Cassandra)
	case types.BackendSQLite:
		return onlineSQLite.Open(opt.SQLite)
	case types.BackendTiKV:
		return onlineTiKV.Open(opt.TiKV)
	default:
		return nil, fmt.Errorf("unsupported backend: %s", opt.Backend)
	}
```

**Comment by YikSanChan** [comment]
@wfxr updated, can you take a second look?

**Review by wfxr — APPROVED** [review]
LGTM!

**Pull request merged**
